### ISSUE TITLE
Test scene crashes in Unity 2019.2.17f1 MacOS 10.14.6

### ISSUE THREAD

**Issue by alexanderflink** [keijiro/AudioJack#5]
AudioJack doesn't seem to work on MacOS Mojave 10.14.6 running Unity 2019.2.17f1. I've tried rebuilding the plugin in Xcode, but the test scene still won't run. I'm trying to use  your [Reaktion](https://github.com/keijiro/Reaktion) Unity package, but it seems to depend on AudioJack. I noticed these two don't seem to be maintained any more. Would be very grateful if you could point me in the right direction as i'm fumbling in the dark. The attached error report i'm getting from Unity isn't telling me much.
[error.txt](https://github.com/keijiro/AudioJack/files/3998367/error.txt)

**Comment by keijiro** [comment]
AudioJack was superseded by LASP: https://github.com/keijiro/Lasp

Could you try LASP with your environment? I'll look into it if it has an issue.

**Comment by alexanderflink** [comment]
Ah, I didn't see that one. Works great! Thank you so much!

**Comment by keijiro** [comment]
Okay. So, I'm closing this issue.
